language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "12"
script:
  - npm run build
deploy:
  provider: script
  script: 'echo hello'
  skip_cleanup: true
  on:
    branch: master